### ISSUE TITLE
Permit unbundling the library

### ISSUE THREAD

**Issue by clausecker** [open-quantum-safe/liboqs-rust#190]
I am currently trying to write a FreeBSD port (i.e. distribution package) for the rosenpass project.  In the process of doing that I noticed that it bundles a static copy of liboqs through your crate.  This is unfortunate.  We would strongly prefer if the project instead linked against `liboqs.so` so we can fix potential security issues in a single place.

Would it be possible for you to permit linking against a shared library instead of building and linking your own static copy of the code?

**Comment by thomwiggers** [comment]
This should be possible by letting `oqs-sys`' `build.rs` find `liboqs` and its header files. We should probably do a `vendor` style feature like the `openssl-sys` crate.

However, I do not have time to make the required changes to do this right now. I would review and potentially merge a PR, but it would also need to expand CI to cover these new build scenarios.

**Comment by clausecker** [comment]
Thank you.  Unfortunately I do not have any Rust experience, so I'll not be able to assist you with this.

**Comment by tranzystorek-io** [comment]
I took a quick glance at this out of curiosity, but liboqs doesn't seem to provide a pkg-config file, and cmake scripts alone aren't easily read from `build.rs` :/

**Comment by wucke13** [comment]
Now that @tranzystorek-io provided https://github.com/open-quantum-safe/liboqs/pull/1435 which was merged (thank you!!!), I think the discussion should continue here. @thomwiggers are there any specific requirements for such a PR? So far I only got

- [ ] has to be checked by CI

**Comment by thomwiggers** [comment]
This should be fixed by #190 right?

**Comment by clausecker** [comment]
@thomwiggers This here is issue #190, so I'm not sure what you meant to link.

**Comment by thomwiggers** [comment]
My bad, #211
