### ISSUE TITLE
Include a way to create a PublicKey (not PublicKeyRef) from bytes.

### ISSUE THREAD

**Issue by marcbrevoort-cyberhive** [open-quantum-safe/liboqs-rust#21]
Currently it is possible to create a PublicKeyRef from bytes using public_key_from_bytes.
It is also possible to derive a PublicKeyRef from PublicKey.

However there seems to be no mechanism at all to generate a PublicKey struct from bytes.

Things that *don't* work include

- public_key_from_bytes (this returns a publickeyref rather than a publickey)
- PublicKey::from(PublicKeyRef) (not implemented)
- just creating the struct, PublicKey { bytes: [u8] } -  bytes is a private field
- PublicKey::new(bytes) - not implemented, PublicKeyRef::new() however does exist
- PublicKeyRef::deref() also does not seem to work to get to the PublicKey instance.

Would it be possible to include PublicKey struct creation from bytes?

**Comment by thomwiggers** [comment]
I think `PublicKeyRef` should generally be preferred as you'll probably usually have them in some networkbuffer or file buffer, and `PublicKey` needs a copy to construct. 

However, I'm adding a `to_owned()`  in #23
