### ISSUE TITLE
Updated liboqs-sys create on crates.io

### ISSUE THREAD

**Issue by xv-pete-m** [open-quantum-safe/liboqs-rust#213]
Hi guys,

I've got a crate that depends on the new version of `liboqs-sys` being published. I'm not sure what the usual publish cadence is for Rust, but I'm super excited to see it 😊 

Thanks in advance!

**Comment by xv-pete-m** [comment]
Sorry guys, thanks for taking the time to move it to the right place 🙏

**Comment by wucke13** [comment]
I'm also eagerly waiting for the rust crate to update to liboqs 0.8.0 :+1:

**Comment by xv-pete-m** [comment]
Any idea when the new crate might be released? 🙏

**Comment by thomwiggers** [comment]
I have recently gotten a new job and I need to figure out some things in relation to contributing to this open-source project; so that's why I've been holding off touching this for now.

Sorry for the delay.

**Comment by xv-pete-m** [comment]
No worries at all!

I greatly appreciate all the time and effort that goes into building and maintaining this, and thank you especially for finding the time to reply so quickly! 🙂

**Comment by xv-pete-m** [comment]
Is there anything I can do to help support you in getting this release out on to crates.io? 🙏

**Comment by xv-pete-m** [comment]
Gentle bump - please let me know if I can help 🙂

**Comment by thomwiggers** [comment]
published 0.8.0, thanks for the patience
