### ISSUE TITLE
Win 10, package compilation step fails to find OpenSSL

### ISSUE THREAD

**Issue by jamesej** [open-quantum-safe/liboqs-rust#77]
I'm on Win 10, VS code. Adding oqs = "*" or oqs-sys = "*" in Cargo.toml causes a build step to occur which fails with this message:

```
CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):        
    Could NOT find OpenSSL, try to set the path to OpenSSL root folder
```
Installing OpenSSL and setting OPENSSL_ROOT_DIR environment variable as the message suggests has no effect.

**Comment by thomwiggers** [comment]
How have you set the build var? Is it visible in whatever the Windows equivalent to `env` is`?

You might also choose to just disable the `openssl` feature.

**Comment by jamesej** [comment]
I set it using setx in a cmd window which should set it globally for my user identity. I then reopened the window in which I was doing the build and checked it was correct in the env. How can I disable the openssl feature? I only have the Cargo.toml entry to work with as far as I can see.

**Comment by thomwiggers** [comment]
```
[dependencies]
oqs = { version = "*", default-features = false }
```

**Comment by jamesej** [comment]
OK it compiles with that setting, many thanks. I believe I get all the algorithms with that setting above in v0.6 which is what is in crates.io right now but that will change with 0.7 where I'll have to pick the algorithms as features, let me know if that's incorrect.

**Comment by thomwiggers** [comment]
Yeah that’s correct.

Op do 29 jul. 2021 om 18:56 schreef jamesej ***@***.***>

**Comment by thomwiggers** [comment]
Closing this as it seems resolved -- OPENSSL_ROOT_DIR _does_ work on Windows after all (because CI is using it).
